<?php

namespace App\Filament\Resources\Documents\Tables;

use Filament\Actions\Action;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class DocumentsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('nadu.nadu_ankaya')
                    ->label('Case No')
                    ->searchable()
                    ->sortable(),

                TextColumn::make('document_type')
                    ->label('Document Type')
                    ->badge()
                    ->searchable(),

                TextColumn::make('file_name')
                    ->label('File Name')
                    ->searchable()
                    ->limit(40),

                TextColumn::make('user.name')
                    ->label('Generated By')
                    ->sortable(),

                TextColumn::make('created_at')
                    ->label('Generated On')
                    ->dateTime('Y-m-d H:i')
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),

                EditAction::make(),

                Action::make('download')
                    ->label('Download')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('success')
                    ->action(function ($record) {
                        return response()->download(
                            storage_path('app/'.$record->file_path),
                            $record->file_name
                        );
                    }),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}