<?php

namespace App\Filament\Widgets;

use App\Models\Company;
use App\Models\Document;
use App\Models\User;
use Filament\Widgets\StatsOverviewWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class SystemOverview extends StatsOverviewWidget
{
    protected function getStats(): array
    {
        $companies = Company::query()
            ->select(['id', 'table_name'])
            ->get();

        $naduCount = $companies->sum(function (Company $company): int {
            if (! preg_match('/^company_\d{4}_cases$/', $company->table_name)
                || ! Schema::connection('companies')->hasTable($company->table_name)) {
                return 0;
            }

            return DB::connection('companies')
                ->table($company->table_name)
                ->count();
        });

        return [
            Stat::make('Companies', number_format($companies->count()))
                ->description('Companies configured in the system')
                ->icon('heroicon-o-building-office-2')
                ->color('primary'),
            Stat::make('Nadu records', number_format($naduCount))
                ->description('Records across all companies')
                ->icon('heroicon-o-folder-open')
                ->color('warning'),
            Stat::make('Documents', number_format(Document::query()->count()))
                ->description('Documents generated by the system')
                ->icon('heroicon-o-document-text')
                ->color('success'),
            Stat::make('Users', number_format(User::query()->count()))
                ->description('Registered system users')
                ->icon('heroicon-o-users')
                ->color('gray'),
        ];
    }
}
